admin:
  access_log_path: /tmp/nighthawk_test_server_admin_access.log
  profile_path: /tmp/nighthawk_test_server.prof
  address:
    socket_address: { address: 0.0.0.0, port_value: 10001 }
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 10080
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          generate_request_id: false
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: service
              domains:
              - "*"
          http_filters:
          - name: time-tracking
          - name: dynamic-delay
          - name: test-server
            config:
              response_body_size: 10
              v3_response_headers:
              - { header: { key: "x-nh", value: "1"}}
          - name: envoy.router
            config:
              dynamic_stats: false
