FROM ubuntu:26.04@sha256:3131b4cc82a783df6c9df078f86e01819a13594b865c2cad47bd1bca2b7063bb

RUN apt -y update && apt -y install libatomic1 curl

ADD nighthawk_client /usr/local/bin/nighthawk_client
ADD nighthawk_test_server /usr/local/bin/nighthawk_test_server
ADD nighthawk_output_transform /usr/local/bin/nighthawk_output_transform
ADD nighthawk_service /usr/local/bin/nighthawk_service
ADD nighthawk_adaptive_load_client /usr/local/bin/nighthawk_adaptive_load_client

ADD default-config.yaml /etc/nighthawk/nighthawk.yaml

# Ports for nighthawk_test_server, see default-config.yaml
EXPOSE 10001 10080
# The default port for nighthawk_service
EXPOSE 8443

ENTRYPOINT ["/usr/local/bin/nighthawk_test_server"]
CMD ["-c", "/etc/nighthawk/nighthawk.yaml"]
