FROM ubuntu:24.04@sha256:72297848456d5d37d1262630108ab308d3e9ec7ed1c3286a32fe09856619a782

RUN apt-get update && apt-get install libatomic1

ADD nighthawk_client /usr/local/bin/nighthawk_client
ADD nighthawk_test_server /usr/local/bin/nighthawk_test_server
ADD nighthawk_output_transform /usr/local/bin/nighthawk_output_transform
ADD nighthawk_service /usr/local/bin/nighthawk_service
ADD nighthawk_adaptive_load_client /usr/local/bin/nighthawk_adaptive_load_client
ADD default-config.yaml /etc/envoy/envoy.yaml

# Ports for nighthawk_test_server, see default-config.yaml
EXPOSE 10001
EXPOSE 10080
# The default port for nighthawk_service
EXPOSE 8443

CMD ["-c", "/etc/envoy/envoy.yaml"]
