// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: api/client/service.proto

#include "api/client/service.pb.h"
#include "client/service.grpc.pb.h"

#include <gmock/gmock.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace nighthawk {
namespace client {

class MockNighthawkServiceStub : public NighthawkService::StubInterface {
 public:
  MOCK_METHOD1(SendCommandRaw, ::grpc::ClientReaderWriterInterface< ::nighthawk::client::SendCommandRequest, ::nighthawk::client::SendCommandResponse>*(::grpc::ClientContext* context));
  MOCK_METHOD3(AsyncSendCommandRaw, ::grpc::ClientAsyncReaderWriterInterface<::nighthawk::client::SendCommandRequest, ::nighthawk::client::SendCommandResponse>*(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag));
  MOCK_METHOD2(PrepareAsyncSendCommandRaw, ::grpc::ClientAsyncReaderWriterInterface<::nighthawk::client::SendCommandRequest, ::nighthawk::client::SendCommandResponse>*(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq));
};

} // namespace nighthawk
} // namespace client

