load("@envoy_api//bazel:api_build_system.bzl", "api_cc_py_proto_library")

licenses(["notice"])

api_cc_py_proto_library(
    name = "statistic",
    srcs = [
        "statistic.proto",
    ],
    visibility = ["//visibility:public"],
)
