name: Nighthawk CI/CD

permissions:
  contents: read

on:
  pull_request:

jobs:
  check:
    permissions:
      contents: read
      packages: read
    runs-on: envoy-x64-medium
    strategy:
      fail-fast: false
      matrix:
        target: [build, check_format]
    steps:
    - uses: actions/checkout@v4
    - name: Run CI script
      run: |
        bazel run \
            --config=remote-envoy-engflow \
            --@envoy//tools/cat:target=//:hello \
            @envoy//tools/cat
      env:
        GITHUB_TOKEN: ${{ github.token }}
